version: "3"
services:
  react-app:
    image: react-app-production
    restart: unless-stopped
    ports:
      - "80:80"
      - "443-443"
    networks:
    - khagu-dev
  api-server:
    image: api-server
    restart: unless-stopped
    env_file: ./server/config/${ENV}.env
    ports:
      - "5500:5500"
    networks:
      - khagu-dev
networks:
  khagu-dev:
    driver: bridge
volumes:
  mongo-data:
    driver: local